# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171202_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='_provider_products_+', to='shop.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
