# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_product_tags_+', to='shop.ProductTag'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='_provider_products_+', to='shop.Product'),
        ),
    ]
