# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='ok', max_length=20),
        ),
    ]
