# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('bar_code', 'shop')]),
        ),
    ]
