# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20171202_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='data_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
