# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shop_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='month_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='week_profit',
            field=models.FloatField(default=0),
        ),
    ]
