# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20171203_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='delivery_period',
            field=models.CharField(default='?', max_length=30),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_delivery_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='next_delivery_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='regularity',
            field=models.CharField(default='?', max_length=30),
        ),
    ]
