# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20171203_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_cost',
            field=models.FloatField(default=100500.0),
        ),
    ]
