# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20171202_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='evotor_user_id',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
