# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_organization_evotor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_link',
            field=models.CharField(blank=True, default=True, max_length=30, null=True),
        ),
    ]
